version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run webpack:prod

cache:
  paths:
    - './node_modules/**/*'